services:
  web:
    image: tomcat:10.1-jdk17
    container_name: tomcat-server
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./target/gigaspring-lab.war:/usr/local/tomcat/webapps/ROOT.war
